name: flutter_study_demo
description: 开眼学习demo

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
  - images/ic_action_search.png
  - images/ic_tab_strip_icon_category.png
  - images/ic_tab_strip_icon_category_selected.png
  - images/ic_tab_strip_icon_feed.png
  - images/ic_tab_strip_icon_feed_selected.png
  - images/ic_tab_strip_icon_follow.png
  - images/ic_tab_strip_icon_follow_selected.png
  - images/ic_tab_strip_icon_profile.png
  - images/ic_tab_strip_icon_profile_selected.png
  - images/ic_home_public.png
  - images/ic_menu_heart.png
  - images/ic_menu_more.png
  - images/ic_menu_download.png
  - images/ic_default_avatar.png
  - images/ic_bg_login.png
  - images/ic_account_login_header.png
  - images/ic_account_login_wechat.png
  - images/ic_account_login_qq.png
  - images/ic_account_login_weibo.png
  - images/no_account_tip.png
  - images/ic_action_focus.png